'use client'

import { useEffect, useState } from 'react'

const scenes = [
  { eyebrow: 'DESCUBRE · 0:00—0:03', title: 'Miles de tiendas.\nUn solo lugar.', body: '¿Quieres comprar en tus tiendas favoritas de Estados Unidos?', visual: 'storefronts', step: '01' },
  { eyebrow: 'ELIGE · 0:03—0:07', title: 'Encuentra lo que quieres.', body: 'Copia el enlace del producto que te gusta.', visual: 'link', step: '02' },
  { eyebrow: 'COTIZA · 0:07—0:11', title: 'Tu cotización,\ndirecto a WhatsApp.', body: 'Con un toque, solicita tu cotización personalizada.', visual: 'whatsapp', step: '03' },
  { eyebrow: 'PAGA · 0:11—0:15', title: 'Compra sin complicaciones.', body: 'Aprueba tu cotización y paga de forma segura.', visual: 'secure', step: '04' },
  { eyebrow: 'RECIBE · 0:15—0:20', title: 'Tú eliges.\nUSALINK lo hace posible.', body: 'Compramos en Estados Unidos y llevamos tu compra hasta tu courier.', visual: 'delivery', step: '05' },
]

function SceneVisual({ type }: { type: string }) {
  if (type === 'storefronts') return <div className="grid grid-cols-2 gap-2 rounded-2xl bg-[#eef1ec] p-3">{['Coach Outlet', 'Nike', 'Sephora', 'Target'].map((name, i) => <div key={name} className="rounded-xl bg-white p-3 shadow-sm"><div className={`mb-3 h-16 rounded-lg ${['bg-[#d9bd9e]', 'bg-[#18202a]', 'bg-[#e9e9e5]', 'bg-[#d92c2c]'][i]}`} /><span className="text-[10px] font-bold text-[#14213d]">{name}</span></div>)}</div>
  if (type === 'link') return <div className="rounded-2xl bg-[#14213d] p-4 text-white shadow-xl"><div className="mb-3 text-[10px] uppercase tracking-[0.18em] text-[#f5c400]">Producto elegido</div><div className="mb-4 rounded-xl bg-white/10 p-3 text-xs text-white/80">https://www.nike.com/us/t/air-max...</div><div className="flex items-center gap-2 rounded-xl bg-[#f5c400] px-4 py-3 text-sm font-black text-[#14213d]">Copiar enlace <span className="ml-auto">→</span></div></div>
  if (type === 'whatsapp') return <div className="rounded-2xl border border-[#d8e5d9] bg-white p-4 shadow-xl"><div className="mb-4 flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#0a8a43] text-lg text-white">W</div><div><b className="block text-sm text-[#14213d]">USALINK</b><span className="text-[10px] text-[#5f6673]">Cotización nueva</span></div></div><div className="rounded-xl bg-[#e6f7e9] p-3 text-xs leading-5 text-[#14213d]">Hola, quiero cotizar este producto:<br /><b>Nike Air Max · Talla 9</b><br />Link listo para revisar.</div></div>
  if (type === 'secure') return <div className="rounded-2xl bg-white p-4 shadow-xl"><div className="mb-3 flex justify-between text-sm font-black text-[#14213d]"><span>Total de tu compra</span><span>RD$8,950</span></div><div className="space-y-2 border-t border-[#e8ece8] pt-3 text-xs text-[#5f6673]"><div className="flex justify-between"><span>Producto</span><span>RD$7,400</span></div><div className="flex justify-between"><span>Gestión + envío</span><span>RD$1,550</span></div></div><div className="mt-4 rounded-xl bg-[#0a8a43] px-4 py-3 text-center text-sm font-black text-white">Pagar de forma segura</div></div>
  return <div className="relative rounded-2xl bg-[#dfece0] p-4"><div className="flex items-center justify-between text-[10px] font-bold uppercase tracking-[0.16em] text-[#0a8a43]"><span>Miami</span><span>República Dominicana</span></div><div className="my-8 flex items-center gap-2"><div className="h-px flex-1 border-t border-dashed border-[#0a8a43]" /><span className="grid h-10 w-10 place-items-center rounded-full bg-[#f5c400] text-lg">✈</span><div className="h-px flex-1 border-t border-dashed border-[#0a8a43]" /></div><div className="rounded-xl bg-white p-3 text-center text-xs font-bold text-[#14213d]">Tu paquete está en camino</div></div>
}

export function PromoVideo() {
  const [active, setActive] = useState(0)
  useEffect(() => { const timer = window.setInterval(() => setActive((value) => (value + 1) % scenes.length), 4000); return () => window.clearInterval(timer) }, [])
  const scene = scenes[active]
  return <section aria-label="Cómo funciona USALINK" className="overflow-hidden bg-[#f6f8f3] px-5 py-12 text-[#14213d] sm:px-8"><div className="mx-auto max-w-6xl"><div className="mb-8 flex items-end justify-between gap-4"><div><p className="mb-2 font-mono text-[10px] font-bold uppercase tracking-[0.2em] text-[#0a8a43]">USALINK / EN 20 SEGUNDOS</p><h2 className="max-w-xl text-balance text-3xl font-black tracking-tight sm:text-5xl">Comprar en USA, hecho fácil.</h2></div><span className="hidden font-mono text-xs text-[#5f6673] sm:block">{scene.eyebrow}</span></div><div className="grid gap-6 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div className="relative overflow-hidden rounded-[2rem] bg-[#14213d] p-6 text-white shadow-2xl sm:p-10"><div className="absolute right-6 top-6 font-mono text-5xl font-black text-white/10">{scene.step}</div><p className="mb-8 font-mono text-[10px] font-bold uppercase tracking-[0.2em] text-[#f5c400]">{scene.eyebrow}</p><h3 className="whitespace-pre-line text-4xl font-black leading-[0.95] tracking-tight sm:text-6xl">{scene.title}</h3><p className="mt-6 max-w-sm text-base leading-7 text-white/70">{scene.body}</p><div className="mt-10 flex gap-2" aria-label="Escenas del video">{scenes.map((item, index) => <button key={item.step} aria-label={`Ver escena ${index + 1}`} aria-pressed={active === index} onClick={() => setActive(index)} className={`h-1.5 rounded-full transition-all ${active === index ? 'w-10 bg-[#f5c400]' : 'w-5 bg-white/25'}`} />)}</div></div><div className="relative min-h-[330px] rounded-[2rem] bg-white p-5 shadow-xl sm:p-10"><div className="mb-5 flex items-center justify-between border-b border-[#e8ece8] pb-4"><span className="font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-[#5f6673]">Vista previa</span><span className="flex items-center gap-2 text-xs font-bold text-[#0a8a43]"><span className="h-2 w-2 rounded-full bg-[#0a8a43]" /> EN VIVO</span></div><div key={active} className="animate-in fade-in slide-in-from-bottom-3 duration-500"><SceneVisual type={scene.visual} /></div></div></div><div className="mt-6 flex flex-wrap items-center justify-between gap-4 border-t border-[#dce4dc] pt-5"><p className="text-sm text-[#5f6673]">Elige. Cotiza. Paga. Recibe.</p><a href="#cotizar" className="rounded-full bg-[#0a8a43] px-5 py-3 text-sm font-black text-white transition hover:bg-[#076c35]">COMPRAR AHORA <span aria-hidden="true">→</span></a></div></div></section>
}

export default PromoVideo
